## Among Myth and Wonder
## ability_catalog

from Resources import ability_classes


actions_cat = {"Direct order - morale" : ability_classes.Ability_Action("Increase morale",
                                                                        None,
                                                                        "Addition",
                                                                        None,
                                                                        [],
                                                                        "Direct order - increase morale"),
               "Direct order - initiative" : ability_classes.Ability_Action("Advance initiative",
                                                                            None,
                                                                            "Decrease",
                                                                            None,
                                                                            [],
                                                                            "Direct order - advance initiative"),
               "Rally" : ability_classes.Ability_Action("Increase army morale",
                                                        None,
                                                        "Addition",
                                                        None,
                                                        [],
                                                        "Rally"),
               "Bless" : ability_classes.Ability_Action("Effect",
                                                        None,
                                                        None,
                                                        None,
                                                        [],
                                                        "Bless"),
               "Haste" : ability_classes.Ability_Action("Effect",
                                                        None,
                                                        None,
                                                        None,
                                                        [],
                                                        "Haste"),
               "Healing" : ability_classes.Ability_Action("Heal",
                                                          None,
                                                          None,
                                                          None,
                                                          [],
                                                          "Healing"),
               "Divine protection" : ability_classes.Ability_Action("Effect",
                                                                    None,
                                                                    None,
                                                                    None,
                                                                    [],
                                                                    "Divine protection"),
               "Divine strength" : ability_classes.Ability_Action("Effect",
                                                                  None,
                                                                  None,
                                                                  None,
                                                                  [],
                                                                  "Divine strength"),
               "Inspiration" : ability_classes.Ability_Action("Increase morale",
                                                              None,
                                                              "Addition",
                                                              None,
                                                              [],
                                                              "Inspiration"),
               "Missile shielding" : ability_classes.Ability_Action("Effect",
                                                                    None,
                                                                    None,
                                                                    None,
                                                                    [],
                                                                    "Missile shielding"),
               "Fire arrows" : ability_classes.Ability_Action("Single target attack",
                                                              None,
                                                              None,
                                                              None,
                                                              [],
                                                              "Fire arrows"),
               "Lightning bolts" : ability_classes.Ability_Action("Single target attack",
                                                                  None,
                                                                  None,
                                                                  None,
                                                                  [],
                                                                  "Lightning bolts"),
               "Hail" : ability_classes.Ability_Action("Single target attack",
                                                       None,
                                                       None,
                                                       None,
                                                       [],
                                                       "Hail")
               }


ability_cat = {"Direct order" : ability_classes.Hero_Ability("Direct order",
                                                             "horn",
                                                             "Abilities/Tactics/",
                                                             "Tactics",
                                                             [actions_cat["Direct order - morale"],
                                                              actions_cat["Direct order - initiative"]],
                                                             [],
                                                             "single_ally",
                                                             0,
                                                             "buff"),
               "Rally" : ability_classes.Hero_Ability("Rally",
                                                      "rally",
                                                      "Abilities/Tactics/",
                                                      "Tactics",
                                                      [actions_cat["Rally"]],
                                                      [],
                                                      "all_allies",
                                                      0,
                                                      "buff"),
               "Bless" : ability_classes.Hero_Ability("Bless",
                                                      "bless",
                                                      "Abilities/Divine/",
                                                      "Divine",
                                                      [actions_cat["Bless"]],
                                                      [],
                                                      "single_ally",
                                                      4,
                                                      "buff"),
               "Haste" : ability_classes.Hero_Ability("Haste",
                                                      "haste",
                                                      "Abilities/Divine/",
                                                      "Divine",
                                                      [actions_cat["Haste"]],
                                                      [],
                                                      "single_ally",
                                                      4,
                                                      "buff"),
               "Healing" : ability_classes.Hero_Ability("Healing",
                                                        "healing",
                                                        "Abilities/Divine/",
                                                        "Divine",
                                                        [actions_cat["Healing"]],
                                                        [],
                                                        "single_ally",
                                                        4,
                                                        "buff"),
               "Divine protection" : ability_classes.Hero_Ability("Divine protection",
                                                                  "divine_protection",
                                                                  "Abilities/Divine/",
                                                                  "Divine",
                                                                  [actions_cat["Divine protection"]],
                                                                  [],
                                                                  "single_ally",
                                                                  4,
                                                                  "buff"),
               "Divine strength" : ability_classes.Hero_Ability("Divine strength",
                                                                "divine_strength",
                                                                "Abilities/Divine/",
                                                                "Divine",
                                                                [actions_cat["Divine strength"]],
                                                                [],
                                                                "single_ally",
                                                                4,
                                                                "buff"),
               "Inspiration" : ability_classes.Hero_Ability("Inspiration",
                                                            "inspiration",
                                                            "Abilities/Divine/",
                                                            "Divine",
                                                            [actions_cat["Inspiration"]],
                                                            [],
                                                            "single_ally",
                                                            4,
                                                            "buff"),
               "Missile shielding" : ability_classes.Hero_Ability("Missile shielding",
                                                                  "missile_shielding",
                                                                  "Abilities/Divine/",
                                                                  "Divine",
                                                                  [actions_cat["Missile shielding"]],
                                                                  [],
                                                                  "single_ally",
                                                                  4,
                                                                  "buff"),
               "Fire arrows" : ability_classes.Hero_Ability("Fire arrows",
                                                            "fire_arrows",
                                                            "Abilities/Elemental/",
                                                            "Elemental",
                                                            [actions_cat["Fire arrows"]],
                                                            [],
                                                            "single_enemy",
                                                            5,
                                                            "damage spell"),
               "Lightning bolts" : ability_classes.Hero_Ability("Lightning bolts",
                                                                "lightning_bolts",
                                                                "Abilities/Elemental/",
                                                                "Elemental",
                                                                [actions_cat["Lightning bolts"]],
                                                                [],
                                                                "single_enemy",
                                                                5,
                                                                "damage spell"),
               "Hail" : ability_classes.Hero_Ability("Hail",
                                                     "hail",
                                                     "Abilities/Elemental/",
                                                     "Elemental",
                                                     [actions_cat["Hail"]],
                                                     [],
                                                     "single_enemy",
                                                     5,
                                                     "damage spell")
               }
