## Miracle battles


artifact_desc = {"Champion's lance" : ["Cavalry regiments gain +1 speed"],
                 "Priest's old hat" : ["Knowledge +1"],
                 "Lucky coin purse" : ["Florins +200 from adventures"],
                 "Sword of haste" : ["Cast Haste spell"],
                 "Bronze spurs" : ["Army's movement points +150"],
                 "Page's chainmail" : ["Ranged infantry gain +2 armour"],
                 "Wooden chalice" : ["Healing spell: +2 MP, -1 mana cost"],
                 "Medal of honor" : ["Leadership +1"],
                 "Red sceptre" : ["Bless spell: +2 MP, -1 mana cost"],
                 "Sapphire ring" : ["Mana reserve +1 replenishment"],
                 "Bone wand" : ["Mana reserve +2 replenishment",
                                "Melee infantry -1 melee mastery"],
                 "Old dwarven chieftain's axe" : ["Melee infantry +2 melee mastery",
                                                  "Melee infantry -1 speed"],
                 "Grimcloud horde's staff" : ["Magic power +2",
                                              "Mana cost +1 for all spells"],
                 "Ancient elven sceptre" : ["Army's movement points +300",
                                            "Leadership +1"],
                 "Broken javelin" : ["Ranged infantry +1 attack range",
                                     "Melee cavalry -1 defence"],
                 "Composite bow" : ["Ranged infantry's ranged attack -15% initiative"],
                 "Elven crown" : ["Hero's abilities -15% initiative"],
                 "Forgotten mask" : ["Caster +2 MP"],
                 "Hat of grand wizard" : ["Knowledge +2"],
                 "Champion's sword" : ["Melee infantry +1 melee mastery",
                                       "Melee infantry +1 defence"]}
