## Among Myth and Wonder
## hero_skill_catalog

from Resources import skill_classes

hero_skill_data = {"Basic logistics": ["logistics", "Skill", "Advanced logistics", "Basic", "Logistics",
                                       ["Basic logistics"],
                                       [],
                                       [skill_classes.Skill_Effect("Movement points",
                                                                   200,
                                                                   "addition",
                                                                   None,
                                                                   [],
                                                                   [])]],
                   "Advanced logistics": ["logistics", "Skill", "Expert logistics", "Advanced", "Logistics",
                                          ["Basic logistics", "Advanced logistics"],
                                          ["Basic logistics"],
                                          [skill_classes.Skill_Effect("Movement points",
                                                                      400,
                                                                      "addition",
                                                                      None,
                                                                      [],
                                                                      [])]],
                   "Expert logistics": ["logistics", "Skill", None, "Expert", "Logistics",
                                        ["Basic logistics", "Advanced logistics", "Expert logistics"],
                                        ["Advanced logistics"],
                                        [skill_classes.Skill_Effect("Movement points",
                                                                    600,
                                                                    "addition",
                                                                    None,
                                                                    [],
                                                                    [])]],
                   "Battle horses": ["battle_horses", "Perk", None, "Perk", "Logistics",
                                     ["Battle horses"],
                                     ["Basic logistics", "Basic assault"],
                                     [skill_classes.Skill_Effect("Bonus speed",
                                                                 2,
                                                                 "addition",
                                                                 None,
                                                                 [],
                                                                 ["melee cavalry", "ranged cavalry"])]],
                   "Basic leadership": ["leadership", "Skill", "Advanced leadership", "Basic", "Leadership",
                                        ["Basic leadership"],
                                        [],
                                        [skill_classes.Skill_Effect("Bonus leadership",
                                                                    1,
                                                                    "addition",
                                                                    None,
                                                                    [],
                                                                    [])]],
                   "Advanced leadership": ["leadership", "Skill", "Expert leadership", "Advanced", "Leadership",
                                           ["Basic leadership", "Advanced leadership"],
                                           ["Basic leadership"],
                                           [skill_classes.Skill_Effect("Bonus leadership",
                                                                       2,
                                                                       "addition",
                                                                       None,
                                                                       [],
                                                                       [])]],
                   "Expert leadership": ["leadership", "Skill", None, "Expert", "Leadership",
                                         ["Basic leadership", "Advanced leadership", "Expert leadership"],
                                         ["Advanced leadership"],
                                         [skill_classes.Skill_Effect("Bonus leadership",
                                                                     3,
                                                                     "addition",
                                                                     None,
                                                                     [],
                                                                     [])]],
                   "Battle fervor": ["battle_fervor", "Perk", None, "Perk", "Leadership",
                                     ["Battle fervor"],
                                     ["Basic leadership"],
                                     [skill_classes.Skill_Effect("Bonus morale restoration",
                                                                 0.2,
                                                                 "addition",
                                                                 None,
                                                                 [],
                                                                 [])]],
                   "Stalwart defenders": ["stalwart_defenders", "Perk", None, "Perk", "Leadership",
                                          ["Stalwart defenders"],
                                          ["Basic leadership", "Basic defence"],
                                          [skill_classes.Skill_Effect("Defence morale restoration",
                                                                      0.5,
                                                                      "addition",
                                                                      None,
                                                                      [],
                                                                      []),
                                           skill_classes.Skill_Effect("Defence action bonus",
                                                                      0.5,
                                                                      "addition",
                                                                      None,
                                                                      [],
                                                                      []),
                                           skill_classes.Skill_Effect("Missile defence bonus",
                                                                      1,
                                                                      "addition",
                                                                      None,
                                                                      [],
                                                                      [])
                                           ]],
                   "Basic defence": ["defence", "Skill", "Advanced defence", "Basic", "Defence",
                                     ["Basic defence"],
                                     [],
                                     [skill_classes.Skill_Effect("Defence",
                                                                 1.1,
                                                                 "multiplication",
                                                                 None,
                                                                 [],
                                                                 [])]],
                   "Advanced defence": ["defence", "Skill", "Expert defence", "Advanced", "Defence",
                                        ["Basic defence", "Advanced defence"],
                                        ["Basic defence"],
                                        [skill_classes.Skill_Effect("Defence",
                                                                    1.2,
                                                                    "multiplication",
                                                                    None,
                                                                    [],
                                                                    [])]],
                   "Expert defence": ["defence", "Skill", None, "Expert", "Defence",
                                      ["Basic defence", "Advanced defence", "Expert defence"],
                                      ["Advanced defence"],
                                      [skill_classes.Skill_Effect("Defence",
                                                                  1.3,
                                                                  "multiplication",
                                                                  None,
                                                                  [],
                                                                  [])]],
                   "Fortitude": ["fortitude", "Perk", None, "Perk", "Defence",
                                 ["Fortitude"],
                                 ["Basic defence"],
                                 [skill_classes.Skill_Effect("Bonus fortitude",
                                                             1,
                                                             "addition",
                                                             None,
                                                             [],
                                                             [])]],
                   "Counterattack mastery": ["counterattack_mastery", "Perk", None, "Perk", "Defence",
                                             ["Counterattack mastery"],
                                             ["Basic defence"],
                                             [skill_classes.Skill_Effect("Bonus counterattack",
                                                                         1,
                                                                         "addition",
                                                                         None,
                                                                         [],
                                                                         [])]],
                   "Basic assault": ["assault", "Skill", "Advanced assault", "Basic", "Assault",
                                     ["Basic assault"],
                                     [],
                                     [skill_classes.Skill_Effect("Melee",
                                                                 1.1,
                                                                 "multiplication",
                                                                 None,
                                                                 ["Melee"],
                                                                 [])]],
                   "Advanced assault": ["assault", "Skill", "Expert assault", "Advanced", "Assault",
                                        ["Basic assault", "Advanced assault"],
                                        ["Basic assault"],
                                        [skill_classes.Skill_Effect("Melee",
                                                                    1.2,
                                                                    "multiplication",
                                                                    None,
                                                                    ["Melee"],
                                                                    [])]],
                   "Expert assault": ["assault", "Skill", None, "Expert", "Assault",
                                      ["Basic assault", "Advanced assault", "Expert assault"],
                                      ["Advanced assault"],
                                      [skill_classes.Skill_Effect("Melee",
                                                                  1.3,
                                                                  "multiplication",
                                                                  None,
                                                                  ["Melee"],
                                                                  [])]],
                   "Battle rage": ["battle_rage", "Perk", None, "Perk", "Assault",
                                   ["Battle rage"],
                                   ["Basic assault"],
                                   [skill_classes.Skill_Effect("Bonus damage",
                                                               1,
                                                               "addition",
                                                               None,
                                                               ["Melee"],
                                                               [])]],
                   "Cavalry advantage": ["cavalry_advantage", "Perk", None, "Perk", "Assault",
                                         ["Cavalry advantage"],
                                         ["Basic assault"],
                                         [skill_classes.Skill_Effect("Bonus max damage",
                                                                     2,
                                                                     "addition",
                                                                     None,
                                                                     ["Melee"],
                                                                     ["melee cavalry", "ranged cavalry"])]],
                   "Fierce attack": ["fierce_attack", "Perk", None, "Perk", "Assault",
                                     ["Fierce attack"],
                                     ["Basic assault"],
                                     [skill_classes.Skill_Effect("Initiative time reduction",
                                                                 0.2,
                                                                 "subtraction",
                                                                 None,
                                                                 ["Melee"],
                                                                 ["melee infantry"])]],
                   "Monstrous strike": ["monstrous_strike", "Perk", None, "Perk", "Assault",
                                        ["Monstrous strike"],
                                        ["Basic assault"],
                                        [skill_classes.Skill_Effect("Bonus armour penetration",
                                                                    1,
                                                                    "addition",
                                                                    None,
                                                                    ["Melee"],
                                                                    ["monster", "gargantuan"])]],
                   "Basic divine magic": ["divine", "Skill", "Advanced divine magic", "Basic", "Divine magic",
                                          ["Basic divine magic"],
                                          [],
                                          [skill_classes.Skill_Effect(None,
                                                                      1,
                                                                      None,
                                                                      "Divine magic",
                                                                      [],
                                                                      [])]],
                   "Advanced divine magic": ["divine", "Skill", "Expert divine magic", "Advanced", "Divine magic",
                                             ["Basic divine magic", "Advanced divine magic"],
                                             ["Basic divine magic"],
                                             [skill_classes.Skill_Effect(None,
                                                                         2,
                                                                         None,
                                                                         "Divine magic",
                                                                         [],
                                                                         [])]],
                   "Expert divine magic": ["divine", "Skill", None, "Expert", "Divine magic",
                                           ["Basic divine magic", "Advanced divine magic", "Expert divine magic"],
                                           ["Advanced divine magic"],
                                           [skill_classes.Skill_Effect(None,
                                                                       3,
                                                                       None,
                                                                       "Divine magic",
                                                                       [],
                                                                       [])]],
                   "Amplified haste": ["haste_mastery", "Perk", None, "Perk", "Divine magic",
                                       ["Amplified haste"],
                                       ["Basic divine magic", "Basic assault"],
                                       [skill_classes.Skill_Effect("Ability bonus initiative",
                                                                   0.5,
                                                                   "subtraction",
                                                                   None,
                                                                   [],
                                                                   ["Haste"]),
                                        skill_classes.Skill_Effect("Ability bonus Magic Power",
                                                                   4,
                                                                   "addition",
                                                                   None,
                                                                   [],
                                                                   ["Haste"])]],
                   "Basic archery": ["archery", "Skill", "Advanced archery", "Basic", "Archery",
                                     ["Basic archery"],
                                     [],
                                     [skill_classes.Skill_Effect("Ranged",
                                                                 1.1,
                                                                 "multiplication",
                                                                 None,
                                                                 ["Ranged"],
                                                                 [])]],
                   "Advanced archery": ["archery", "Skill", "Expert archery", "Advanced", "Archery",
                                        ["Basic archery", "Advanced archery"],
                                        ["Basic archery"],
                                        [skill_classes.Skill_Effect("Ranged",
                                                                    1.2,
                                                                    "multiplication",
                                                                    None,
                                                                    ["Ranged"],
                                                                    [])]],
                   "Expert archery": ["archery", "Skill", None, "Expert", "Archery",
                                      ["Basic archery", "Advanced archery", "Expert archery"],
                                      ["Advanced archery"],
                                      [skill_classes.Skill_Effect("Ranged",
                                                                  1.3,
                                                                  "multiplication",
                                                                  None,
                                                                  ["Ranged"],
                                                                  [])]],
                   "Skirmish volley": ["skirmish_volley", "Perk", None, "Perk", "Archery",
                                       ["Skirmish volley"],
                                       ["Basic archery"],
                                       [skill_classes.Skill_Effect("Bonus armour penetration",
                                                                   1,
                                                                   "addition",
                                                                   None,
                                                                   ["Ranged"],
                                                                   ["hybrid infantry"])]],
                   "Marksmanship": ["marksmanship", "Perk", None, "Perk", "Archery",
                                    ["Marksmanship"],
                                    ["Basic archery"],
                                    [skill_classes.Skill_Effect("Bonus accuracy",
                                                                20,
                                                                "addition",
                                                                None,
                                                                ["Ranged"],
                                                                ["ranged infantry"])]],
                   "Basic elemental magic": ["elemental", "Skill", "Advanced elemental magic", "Basic",
                                             "Elemental magic",
                                             ["Basic elemental magic"],
                                             [],
                                             [skill_classes.Skill_Effect(None,
                                                                         1,
                                                                         None,
                                                                         "Elemental magic",
                                                                         [],
                                                                         [])]],
                   "Advanced elemental magic": ["elemental", "Skill", None, "Advanced",
                                                "Elemental magic",
                                                ["Basic elemental magic", "Advanced elemental magic"],
                                                ["Basic elemental magic"],
                                                [skill_classes.Skill_Effect(None,
                                                                            2,
                                                                            None,
                                                                            "Elemental magic",
                                                                            [],
                                                                            [])]],
                   "Basic siege warfare": ["siege_warfare", "Skill", "Advanced siege warfare", "Basic",
                                           "Siege warfare",
                                           ["Basic siege warfare"],
                                           [],
                                           [skill_classes.Skill_Effect("Siege attrition",
                                                                       2,
                                                                       "subtraction",
                                                                       None,
                                                                       [],
                                                                       []),
                                            skill_classes.Skill_Effect("Siege construction points",
                                                                       1.2,
                                                                       "multiplication",
                                                                       None,
                                                                       [],
                                                                       []),
                                            skill_classes.Skill_Effect("Trebuchet attack",
                                                                       1,
                                                                       "addition",
                                                                       None,
                                                                       [],
                                                                       [])]],
                   "Advanced siege warfare": ["siege_warfare", "Skill", "Expert siege warfare", "Advanced",
                                              "Siege warfare",
                                              ["Basic siege warfare", "Advanced siege warfare"],
                                              ["Basic siege warfare"],
                                              [skill_classes.Skill_Effect("Siege attrition",
                                                                          4,
                                                                          "subtraction",
                                                                          None,
                                                                          [],
                                                                          []),
                                               skill_classes.Skill_Effect("Siege construction points",
                                                                          1.4,
                                                                          "multiplication",
                                                                          None,
                                                                          [],
                                                                          []),
                                               skill_classes.Skill_Effect("Trebuchet attack",
                                                                          2,
                                                                          "addition",
                                                                          None,
                                                                          [],
                                                                          [])]],
                   "Expert siege warfare": ["siege_warfare", "Skill", None, "Expert",
                                            "Siege warfare",
                                            ["Basic siege warfare", "Advanced siege warfare"],
                                            ["Basic siege warfare"],
                                            [skill_classes.Skill_Effect("Siege attrition",
                                                                        6,
                                                                        "subtraction",
                                                                        None,
                                                                        [],
                                                                        []),
                                             skill_classes.Skill_Effect("Siege construction points",
                                                                        1.6,
                                                                        "multiplication",
                                                                        None,
                                                                        [],
                                                                        []),
                                             skill_classes.Skill_Effect("Trebuchet attack",
                                                                        3,
                                                                        "addition",
                                                                        None,
                                                                        [],
                                                                        [])]]
                   }
