## Among Myth and Wonder
## hero_skill_information


skill_desc = {"Basic logistics" : ["Every round army gains",
                                   "+200 movement points"],
              "Advanced logistics" : ["Every round army gains",
                                      "+400 movement points"],
              "Expert logistics" : ["Every round army gains",
                                    "+600 movement points"],
              "Basic leadership" : ["Leadership in battle +1"],
              "Advanced leadership" : ["Leadership in battle +2"],
              "Expert leadership" : ["Leadership in battle +3"],
              "Battle horses" : ["Cavalry regiments gain +2 speed"],
              "Battle fervor" : ["Morale recovery +0.2"],
              "Basic defence" : ["Defence +10%"],
              "Advanced defence" : ["Defence +20%"],
              "Expert defence" : ["Defence +30%"],
              "Fortitude" : ["Troops’ Hit Points +1"],
              "Counterattack mastery" : ["One additional counterattack"],
              "Basic assault" : ["Melee attack +10%"],
              "Advanced assault" : ["Melee attack +20%"],
              "Expert assault" : ["Melee attack +30%"],
              "Battle rage" : ["Min and max melee damage +1"],
              "Cavalry advantage" : ["Cavalry regiments gain",
                                     "max melee damage +2"],
              "Fierce attack" : ["Melee attack initiative time -0.2",
                                 "for melee infantry"],
              "Monstrous strike" : ["Melee attack armour penetration +1",
                                    "for monsters and gargantuan"],
              "Basic devine magic" : ["Learn basic devine spells"],
              "Advanced devine magic" : ["Learn Advanced devine spells"],
              "Amplified haste" : ["Hero can use Haste spell as",
                                   "having 4 more magic power",
                                   "and spending 50% less initiative"],
              "Basic archery" : ["Ranged attack +10%"],
              "Advanced archery" : ["Ranged attack +20%"],
              "Expert archery" : ["Ranged attack +30%"],
              "Skirmish volley" : ["Armour penetration +1",
                                   "for hybrid infantry"],
              "Marksmanship" : ["Accuracy +20%",
                                "for ranged infantry",
                                "easier to hit at far range"],
              "Basic elemental magic" : ["Learn basic elemental spells"],
              "Advanced elemental magic" : ["Learn advanced elemental spells"],
              "Basic siege warfare" : ["Lower siege attrition lethality:",
                                       "(10%-20%) → (8%-18%)",
                                       "Siege construction points +20%",
                                       "Trebuchet attack level +25%"],
              "Advanced siege warfare" : ["Lower siege attrition lethality:",
                                          "(10%-20%) → (6%-16%)",
                                          "Siege construction points +40%",
                                          "Trebuchet attack level +50%"],
              "Expert siege warfare" : ["Lower siege attrition lethality:",
                                        "(10%-20%) → (4%-14%)",
                                        "Siege construction points +60%",
                                        "Trebuchet attack level +75%"]
              }
