## Among Myth and Wonder

desc_catalog = {"Base Knight Lords control" : ["Province populated by",
                                               "Knight Lords realm",
                                               "Knight Lords base culture level 4"],
                "Forest law restored" : ["Peasant estate -1 loyalty",
                                         "Blocked replenishment",
                                         "for peasant regiments",
                                         "Duration 8 turns"],
                "Poachers in Royal forest" : ["Nobility estate -1 loyalty",
                                              "Until poachers are defeated"],
                "Frivolous monks" : ["Replenishment +2 turns",
                                     "for battle monks"],
                "Rule of Monastic Life" : ["Knight Lords culture level +1"],
                "Disciplined monks" : ["Clergy estate -1 loyalty",
                                       "Duration 8 turns"],
                "Bribed local lord" : ["Nobility estate +2 loyalty",
                                       "Duration 8 turns"],
                "Transferred abbey's land holdings" : ["Clergy estate -1 loyalty",
                                                       "Duration 12 turns"],
                "Monastery school" : ["New Priests of Salvation starting level +1"],
                "Slay the Grey dragon" : ["Nobility estate -1 loyalty",
                                          "Peasant estate -1 loyalty"],
                "Slayer of the Grey dragon" : ["Nobility estate +1 loyalty"],
                "Provided retinue to vassal" : ["Blocked replenishment",
                                                "for men-at-arms regiments",
                                                "Duration 10 turns"],
                "Rejected request for stone" : ["Nobility estate -2 loyalty",
                                                "Duration 20 turns"],
                "Vassal awaits for stone" : ["Nobility estate -1 loyalty"],
                "Failed to provide stone" : ["Nobility estate -2 loyalty"]
                }
