## Miracle battles


knight_weights = {"Basic logistics" : 7,
                  "Advanced logistics" : 7,
                  "Expert logistics": 7,
                  "Battle horses" : 10,
                  "Basic leadership" : 10,
                  "Advanced leadership" : 10,
                  "Expert leadership": 10,
                  "Battle fervor": 10,
                  "Basic defence" : 10,
                  "Advanced defence" : 10,
                  "Expert defence": 10,
                  "Fortitude" : 10,
                  "Counterattack mastery" : 10,
                  "Basic assault" : 9,
                  "Advanced assault" : 9,
                  "Expert assault": 9,
                  "Battle rage" : 9,
                  "Cavalry advantage" : 10,
                  "Fierce attack" : 9,
                  "Monstrous strike" : 7,
                  "Basic devine magic" : 7,
                  "Advanced devine magic" : 7,
                  "Amplified haste" : 7,
                  "Basic archery" : 6,
                  "Advanced archery" : 6,
                  "Expert archery": 6,
                  "Skirmish volley" : 6,
                  "Marksmanship" : 6,
                  "Basic elemental magic" : 4,
                  "Advanced elemental magic" : 4,
                  "Basic siege warfare": 8,
                  "Advanced siege warfare" : 8,
                  "Expert siege warfare" : 8}


priest_of_salvation_weights = {"Basic logistics" : 7,
                               "Advanced logistics" : 7,
                               "Expert logistics": 7,
                               "Battle horses" : 8,
                               "Basic leadership" : 9,
                               "Advanced leadership" : 9,
                               "Expert leadership": 9,
                               "Battle fervor": 9,
                               "Basic defence" : 8,
                               "Advanced defence" : 8,
                               "Expert defence": 8,
                               "Fortitude" : 8,
                               "Counterattack mastery" : 8,
                               "Basic assault" : 6,
                               "Advanced assault" : 6,
                               "Expert assault": 6,
                               "Battle rage" : 6,
                               "Cavalry advantage" : 6,
                               "Fierce attack" : 6,
                               "Monstrous strike" : 4,
                               "Basic devine magic" : 10,
                               "Advanced devine magic" : 10,
                               "Amplified haste" : 10,
                               "Basic archery" : 5,
                               "Advanced archery" : 5,
                               "Expert archery": 5,
                               "Skirmish volley" : 5,
                               "Marksmanship" : 5,
                               "Basic elemental magic" : 8,
                               "Advanced elemental magic" : 8,
                               "Basic siege warfare": 6,
                               "Advanced siege warfare" : 6,
                               "Expert siege warfare" : 6}


class_cat = {"Knight" : knight_weights,
             "Priest of Salvation" : priest_of_salvation_weights}
