## Among Myth and Wonder
## archetype_skill_weights

random_weights = {"Basic logistics": 1,
                  "Advanced logistics": 1,
                  "Expert logistics": 1,
                  "Battle horses": 1,
                  "Basic leadership": 1,
                  "Advanced leadership": 1,
                  "Expert leadership": 1,
                  "Battle fervor": 1,
                  "Stalwart defenders": 1,
                  "Basic defence": 1,
                  "Advanced defence": 1,
                  "Expert defence": 1,
                  "Fortitude": 1,
                  "Counterattack mastery": 1,
                  "Basic assault": 1,
                  "Advanced assault": 1,
                  "Expert assault": 1,
                  "Battle rage": 1,
                  "Cavalry advantage": 1,
                  "Fierce attack": 1,
                  "Monstrous strike": 1,
                  "Basic divine magic": 1,
                  "Advanced divine magic": 1,
                  "Expert divine magic": 1,
                  "Amplified haste": 1,
                  "Basic archery": 1,
                  "Advanced archery": 1,
                  "Expert archery": 1,
                  "Skirmish volley": 1,
                  "Marksmanship": 1,
                  "Basic elemental magic": 1,
                  "Advanced elemental magic": 1,
                  "Basic siege warfare": 1,
                  "Advanced siege warfare": 1,
                  "Expert siege warfare": 1}

cavalry_focus_weights = {"Basic logistics": 7,
                         "Advanced logistics": 7,
                         "Expert logistics": 7,
                         "Battle horses": 10,
                         "Basic leadership": 6,
                         "Advanced leadership": 6,
                         "Expert leadership": 6,
                         "Battle fervor": 6,
                         "Stalwart defenders": 3,
                         "Basic defence": 6,
                         "Advanced defence": 6,
                         "Expert defence": 6,
                         "Fortitude": 6,
                         "Counterattack mastery": 6,
                         "Basic assault": 9,
                         "Advanced assault": 9,
                         "Expert assault": 9,
                         "Battle rage": 6,
                         "Cavalry advantage": 10,
                         "Fierce attack": 4,
                         "Monstrous strike": 4,
                         "Basic divine magic": 3,
                         "Advanced divine magic": 3,
                         "Expert divine magic": 3,
                         "Amplified haste": 2,
                         "Basic archery": 4,
                         "Advanced archery": 4,
                         "Expert archery": 4,
                         "Skirmish volley": 4,
                         "Marksmanship": 4,
                         "Basic elemental magic": 3,
                         "Advanced elemental magic": 3,
                         "Basic siege warfare": 4,
                         "Advanced siege warfare": 4,
                         "Expert siege warfare": 4}

mixed_troops_weights = {"Basic logistics": 5,
                        "Advanced logistics": 5,
                        "Expert logistics": 5,
                        "Battle horses": 5,
                        "Basic leadership": 6,
                        "Advanced leadership": 6,
                        "Expert leadership": 6,
                        "Battle fervor": 6,
                        "Stalwart defenders": 6,
                        "Basic defence": 6,
                        "Advanced defence": 6,
                        "Expert defence": 6,
                        "Fortitude": 6,
                        "Counterattack mastery": 6,
                        "Basic assault": 6,
                        "Advanced assault": 6,
                        "Expert assault": 6,
                        "Battle rage": 6,
                        "Cavalry advantage": 5,
                        "Fierce attack": 7,
                        "Monstrous strike": 5,
                        "Basic divine magic": 3,
                        "Advanced divine magic": 3,
                        "Expert divine magic": 3,
                        "Amplified haste": 4,
                        "Basic archery": 6,
                        "Advanced archery": 6,
                        "Expert archery": 6,
                        "Skirmish volley": 7,
                        "Marksmanship": 7,
                        "Basic elemental magic": 3,
                        "Advanced elemental magic": 3,
                        "Basic siege warfare": 5,
                        "Advanced siege warfare": 5,
                        "Expert siege warfare": 5}

ranged_troops_weights = {"Basic logistics": 5,
                         "Advanced logistics": 5,
                         "Expert logistics": 5,
                         "Battle horses": 4,
                         "Basic leadership": 6,
                         "Advanced leadership": 6,
                         "Expert leadership": 6,
                         "Battle fervor": 6,
                         "Stalwart defenders": 6,
                         "Basic defence": 6,
                         "Advanced defence": 6,
                         "Expert defence": 6,
                         "Fortitude": 6,
                         "Counterattack mastery": 6,
                         "Basic assault": 6,
                         "Advanced assault": 6,
                         "Expert assault": 6,
                         "Battle rage": 6,
                         "Cavalry advantage": 4,
                         "Fierce attack": 4,
                         "Monstrous strike": 4,
                         "Basic divine magic": 3,
                         "Advanced divine magic": 3,
                         "Expert divine magic": 3,
                         "Amplified haste": 2,
                         "Basic archery": 9,
                         "Advanced archery": 9,
                         "Expert archery": 9,
                         "Skirmish volley": 10,
                         "Marksmanship": 10,
                         "Basic elemental magic": 3,
                         "Advanced elemental magic": 3,
                         "Basic siege warfare": 5,
                         "Advanced siege warfare": 5,
                         "Expert siege warfare": 5}

balanced_magic_focus_weights = {"Basic logistics": 5,
                                "Advanced logistics": 5,
                                "Expert logistics": 5,
                                "Battle horses": 3,
                                "Basic leadership": 4,
                                "Advanced leadership": 4,
                                "Expert leadership": 4,
                                "Battle fervor": 4,
                                "Stalwart defenders": 3,
                                "Basic defence": 3,
                                "Advanced defence": 3,
                                "Expert defence": 3,
                                "Fortitude": 3,
                                "Counterattack mastery": 3,
                                "Basic assault": 3,
                                "Advanced assault": 3,
                                "Expert assault": 3,
                                "Battle rage": 3,
                                "Cavalry advantage": 3,
                                "Fierce attack": 3,
                                "Monstrous strike": 3,
                                "Basic divine magic": 7,
                                "Advanced divine magic": 7,
                                "Expert divine magic": 7,
                                "Amplified haste": 7,
                                "Basic archery": 3,
                                "Advanced archery": 3,
                                "Expert archery": 3,
                                "Skirmish volley": 3,
                                "Marksmanship": 3,
                                "Basic elemental magic": 7,
                                "Advanced elemental magic": 7,
                                "Basic siege warfare": 4,
                                "Advanced siege warfare": 4,
                                "Expert siege warfare": 4}

magic_power_focus_weights = {"Basic logistics": 5,
                             "Advanced logistics": 5,
                             "Expert logistics": 5,
                             "Battle horses": 3,
                             "Basic leadership": 4,
                             "Advanced leadership": 4,
                             "Expert leadership": 4,
                             "Battle fervor": 4,
                             "Stalwart defenders": 3,
                             "Basic defence": 3,
                             "Advanced defence": 3,
                             "Expert defence": 3,
                             "Fortitude": 3,
                             "Counterattack mastery": 3,
                             "Basic assault": 3,
                             "Advanced assault": 3,
                             "Expert assault": 3,
                             "Battle rage": 3,
                             "Cavalry advantage": 3,
                             "Fierce attack": 3,
                             "Monstrous strike": 3,
                             "Basic divine magic": 7,
                             "Advanced divine magic": 7,
                             "Expert divine magic": 7,
                             "Amplified haste": 7,
                             "Basic archery": 3,
                             "Advanced archery": 3,
                             "Expert archery": 3,
                             "Skirmish volley": 3,
                             "Marksmanship": 3,
                             "Basic elemental magic": 7,
                             "Advanced elemental magic": 7,
                             "Basic siege warfare": 4,
                             "Advanced siege warfare": 4,
                             "Expert siege warfare": 4}

class_cat = {"Random": random_weights,
             "Cavalry focus": cavalry_focus_weights,
             "Mixed troops": mixed_troops_weights,
             "Ranged troops": ranged_troops_weights,
             "Balanced magic focus": balanced_magic_focus_weights,
             "Magic power focus": magic_power_focus_weights}
